apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: utcc-it-dev
  labels:
    app: websrv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: websrv
  template:
    metadata:
      labels:
        app: wevsrv
    spec:
      containers:
      - name: websrv
        image: nktdkr23/php-apache:latest
        ports:
        - containerPort: 80
